# Generated by Django 4.0.5 on 2022-11-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='team_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_ID',
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=14)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTracker.player')),
            ],
        ),
    ]
