# Generated by Django 4.0.5 on 2022-11-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProTracker', '0003_playeraccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='account_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='playeraccount',
            name='account_region',
            field=models.CharField(max_length=4),
        ),
    ]
