# Generated by Django 4.0.5 on 2022-11-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProTracker', '0004_alter_playeraccount_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinfo',
            name='player',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='match_duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='match_region',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='match_start_time',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MatchParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.PositiveSmallIntegerField()),
                ('primary_rune', models.PositiveSmallIntegerField()),
                ('primary_rune_slot_1', models.PositiveSmallIntegerField()),
                ('primary_rune_slot_2', models.PositiveSmallIntegerField()),
                ('primary_rune_slot_3', models.PositiveSmallIntegerField()),
                ('secondary_rune', models.PositiveSmallIntegerField()),
                ('secondary_rune_slot_1', models.PositiveSmallIntegerField()),
                ('secondary_rune_slot_2', models.PositiveSmallIntegerField()),
                ('secondary_rune_slot_3', models.PositiveSmallIntegerField()),
                ('summoner_spell_1', models.PositiveSmallIntegerField()),
                ('summoner_spell_2', models.PositiveSmallIntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTracker.matchinfo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTracker.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipantItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveSmallIntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTracker.matchinfo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTracker.player')),
            ],
        ),
    ]
